# Clave del proyecto y organización
sonar.projectKey=Diskiro_EasyOrder_con_back
sonar.organization=diskiro

# Rutas confirmadas del monorepo
sonar.sources=frontend/src,backend/src

# Excluir archivos no analizables
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.nx/**,coverage/**,**/*.test.*,vite.config.ts

# Forzar el entorno de JavaScript/TypeScript (LCOV)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
