name: CI/CD Pipeline & Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # ------ JOB 1: Análisis de Seguridad (Se ejecuta en la Nube de GitHub) ------
  sonarCloudAnalysis:
    name: SonarCloud Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para el historial de Sonar

      - name: Ejecutar Análisis SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  # ------ JOB 2: Despliegue (Se ejecuta DENTRO de tu red local Debian) ------
  deploy:
    name: Deploy Local Server
    runs-on: self-hosted # Redirige la tubería a tu Debian local (josh)
    needs: sonarCloudAnalysis # SRP: Solo despliega si Sonar aprueba el Quality Gate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Actualizar Código y Levantar Contenedores
        # Multiples comandos separados por ;
        run: |
          cd /home/josh/Proyectos/EasyOrder_con_back ; git fetch origin ; git reset --hard origin/main
          docker compose down ; docker compose pull ; docker compose up -d --build
          docker image prune -f
